#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "vaultwarden"
name = "Vaultwarden"
description.en = "Encrypted end-to-end password manager"
description.fr = "Gestionnaire de mots de passe chiffré de bout en bout"

version = "1.37.2~ynh1"

maintainers = [ ]

[upstream]
license = "GPL-3.0-or-later"
admindoc = "https://github.com/dani-garcia/vaultwarden/wiki"
userdoc = "https://help.bitwarden.com/"
code = "https://github.com/dani-garcia/vaultwarden"

[integration]
yunohost = ">= 12.1.40"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true

ldap = false
sso = true

disk = "50M"
ram.build = "80M"
ram.runtime = "70M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/vaultwarden"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    #https://github.com/czyt/vaultwarden-binary/
    in_subdir = false
    amd64.url = "https://github.com/czyt/vaultwarden-binary/releases/download/1.37.2-extracted/vaultwarden-linux-amd64-extracted.zip"
    amd64.sha256 = "be0455665db8702796ff572cce355ba216ce1635ad41f92671200e622309f39e"
    arm64.url = "https://github.com/czyt/vaultwarden-binary/releases/download/1.37.2-extracted/vaultwarden-linux-arm64-extracted.zip"
    arm64.sha256 = "7f9c9547925156a380f1d438471dbcdecec2a3357d444781604d793d2bb3a2ff"
    armhf.url = "https://github.com/czyt/vaultwarden-binary/releases/download/1.37.2-extracted/vaultwarden-linux-armv7-extracted.zip"
    armhf.sha256 = "d75e71f168084135b3b6ce4b5060b56cc248c851e04ef911de584d28a7460d14"

    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/czyt/vaultwarden-binary"
    autoupdate.asset.amd64 = "^vaultwarden-linux-amd64-extracted.zip"
    autoupdate.asset.arm64 = "^vaultwarden-linux-arm64-extracted.zip"
    autoupdate.asset.armhf = "^vaultwarden-linux-armv7-extracted.zip"
    autoupdate.version_regex="(\\d+\\.\\d+\\.\\d+)-extracted"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.data_dir]

    [resources.ports]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.additional_urls = [ "/identity" ]
    api.allowed = "visitors"
    api.auth_header = false
    api.show_tile = false
    api.protected = true
    admin.url = "/admin"
    admin.allowed = "admins"
    admin.show_tile = false

    [resources.apt]
    packages = "argon2"
