#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.efd27d79ee9e6825f3032414646f0bd97db4df4d.name = "Upgrade from 1.37.2~ynh1"
