vaultwarden_url = "https://__DOMAIN____PATH__" # Could this just be localhost:port?
vaultwarden_admin_token = "__ADMIN_TOKEN__"
ldap_host = "localhost"
ldap_bind_dn = ""
ldap_bind_password = ""
ldap_search_base_dn = "ou=users,dc=yunohost,dc=org"
ldap_search_filter = "(&(|(objectclass=posixAccount))(uid=%uid)(permission=cn=$__APP__.main,ou=permission,dc=yunohost,dc=org))"
