#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# MODIFY A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

ynh_config_add --template="vaultwarden.env" --destination="$install_dir/.env"

# Fix SMTP configuration
config_file=$data_dir/config.json
if [ -e "$config_file" ]; then
	cat <<< $(jq -r --arg domain "$domain" '.smtp_host = $domain' $config_file) > $config_file
	cat <<< $(jq -r '.smtp_security = "starttls"' $config_file) > $config_file
	if [ ! -s "$config_file" ]; then
		ynh_die "Something went wrong while setting up $config_file: it ended up empty."
	fi
fi

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
