#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
# REMOVE SYSTEMD SERVICE 
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_exec_warn_less yunohost service status $app >/dev/null
then
	ynh_script_progression --message="Removing $app service integration..."
	yunohost service remove $app
fi

# Remove the dedicated systemd config
ynh_remove_systemd_config

# Remove the dedicated NGINX config
ynh_remove_nginx_config

# Remove the dedicated Fail2Ban config
ynh_remove_fail2ban_config

# Remove the log files
ynh_secure_remove --file="/var/log/$app"

# Remove the config file
ynh_secure_remove --file="/$data_dir/config.json"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed"
