#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

ynh_config_remove_fail2ban

ynh_config_remove_logrotate

if ynh_hide_warnings yunohost service status $app >/dev/null; then
	yunohost service remove $app
fi

ynh_config_remove_systemd

ynh_config_remove_nginx

# Remove dex configuration
ynh_safe_rm "$dex_install_dir/config.yaml.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
